---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: k8s-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: mem-cache
  template:
    metadata:
      labels:
        app: redis
        role: mem-cache
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - name: redis
          containerPort: 6379
      - name: metrics
        image: metrics:latest
        env:
        - name: SERVER_PORT
          value: "5000"
        - name: REDIS_HOST
          value: "localhost"
        ports:
        - containerPort: 5000
          name: metrics 
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: k8s-adapter
spec:
  selector:
    app: redis
    role: mem-cache
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-svc
  namespace: k8s-adapter
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - name: metrics
    port: 9100
    nodePort: 32000
    protocol: TCP
    targetPort: 5000